name: build

on:
  push:
    branches:
    pull_request:
      - main

jobs:
  build:
    runs-on: macos-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Project
        run: ./gradlew build
